### ISSUE TITLE
Use DbUp scripts to manage SchemaVersion table

### ISSUE THREAD

**Issue by hrc3** [DbUp/DbUp#131]
DbUp should [eat it's own dogfood](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) where the SchemaVersion table is concerened. 
- Create/modify the SchemaVersion table using database scripts.
- Dynamically inject the SchemaVersion script(s) to run _before_ any user-specified scripts.
- Include script to transformation any existing SchemaVersion data
- Add tests around the upgrade scenario

**Comment by dazinator** [comment]
The trouble with dbup migrating the schema versions table is that for each script that it runs it needs to record the fact it has run that script and it does that based in inserting into that table. How noy sure how it can reliably insert into a table that is changing from underneath it during execution?

Perhaps we treat schema changes to the schemaversions table by changing the code to use a new table name. I.e SchemaVersions2 and then inject the migration scripts. That way the new table schema will be created, and then the upgrade script can migrate in data from the old table perhaps.. not sure

**Comment by rickculpepper** [comment]
DbUp dynamically creates `SchemaVersions` today at the beginning of the update process. Definitely, we'd have to figure out how to "bootstrap" the `SchemaVersions` table. 

A given release of DbUp should only work with on version of the `SchemaVersions` table -- the one that it expects. The create/upgrade scripts mentioned above, would be executed as prerequisite to DbUp recording any scripts being run. DbUp would have to cache the script executions for the prerequisites so that they could be added to `SchemaVersions` after the process was complete. On the other hand, the `SchemaVersions` create/update scripts could use `NullJournal()` and bypass the `SchemaVersions` table completely, but that would mean that DbUp has to to have another mechanism for knowing the current version of `SchemaVersions`, perhaps through extended properties.

These are all just problems to be solved. ;)

**Comment by dazinator** [comment]
>A given release of DbUp should only work with on version of the SchemaVersions table -- the one that it expects.

I agree - which I think lends itself to the idea that if there are schema changes to this table, then dbup starts with a whole new table perhaps and then migrates the data - because then atleast the table can be created with the correct schema, for any migration scripts that we inject at the start to then apply.

> DbUp would have to cache the script executions for the prerequisites so that they could be added to SchemaVersions after the process was complete. On the other hand, the SchemaVersions create/update scripts could use NullJournal() and bypass the SchemaVersions table completely, but that would mean that DbUp has to to have another mechanism for knowing the current version of SchemaVersions.

None of that is necessary if let DbUp create a new schema versions table at the start with the desire schema, and then write a migration script to be run first that will move the data accross from the older table and then even perhaps drop the older table afterwards..

>These are all just problems to be solved. ;)

Haha yep. This is just one proposed solution, am open to other suggestions.

**Comment by rickculpepper** [comment]
> > A given release of DbUp should only work with on version of the SchemaVersions table -- the one that it expects.

> I agree - which I think lends itself to the idea that if there are schema changes to this table, then dbup starts with a whole new table perhaps and then migrates the data - because then atleast the table can be created with the correct schema, for any migration scripts that we inject at the start to then apply.

So, the way that DbUp would recognize whether it needed to upgrade the SchemaVersions table would be by the name?

> >  DbUp would have to cache the script executions for the prerequisites so that they could be added to SchemaVersions after the process was complete. On the other hand, the SchemaVersions create/update scripts could use NullJournal() and bypass the SchemaVersions table completely, but that would mean that DbUp has to to have another mechanism for knowing the current version of SchemaVersions.

> None of that is necessary if let DbUp create a new schema versions table at the start with the desire schema, and then write a migration script to be run first that will move the data across from the older table and then even perhaps drop the older table afterwards..

I'd have to think about this for a while. Seems like there'd be problems with journaling to the SchemaVersions table since the DbUp scripts would journal to the "before" format and the user scripts to the "after" format. This would be complicated if the SchemaVersions table required upgrading through multiple versions, e.g., 2.0 -> 5.3.

This is all a good, theoretical discussion. I think the proof of the pudding is in the eating... or, really, the writing of the functionality. Lots of details to be worked out. I have a sense that this may be more complicated than we realize at this moment. Of course, I've been completely wrong about things much more important than this! ;)

**Comment by rickculpepper** [comment]
In the end, I think that upgrade scripts that manage the schema and transform any existing data would be the best way to handle this -- as a prerequisite to the execution of user-specified scripts. Now, how to deal with the pesky problem of how to journal these changes to the SchemaVersions table... ;)

**Comment by dazinator** [comment]
Yeah it gets even more interesting because the `SchemaVersions` table may technicaly be called anything if a custom name has been specified in the API.. Also we can't rule out the fact that the user is using a custom `IJournal` implementation - in which case who is to say there is even a `SchemaVersions` table at all..

I am also thinking about this problem, and am veering down the line that the `IJournal` interface needs some method like `EnsureIsUpgraded()` so that for example, so that `TableJournal` can implement that and in that specific scenario it can deal with running the upgrade scripts to its `SchemaVersion` tables..

Just food for thought.. I will see what you come up with anyway.. If you get bored let me know and I will try my luck at tackling this too.

**Comment by rickculpepper** [comment]
@dazinator I don't see the schema table name as a problem -- just use a variable reference to insert the name specified by the caller. 

Custom IJournal implementations, however, are an entirely different situation. The implementer would, of necessity, have to provide the logic for an upgrade. Perhaps a new interface, `IUpgradeableJournal`(?), would be required to avoid a breaking change...

**Comment by JakeGinnivan** [comment]
Maybe we could have a `DelayedWriteJournal` which only writes when all scripts have been run. This allows us to fully upgrade the schema table then we insert the records into the schema table once it is updated. This could live in the `DoesTableExist` method in the Journal? We rename that to `PrepareSchemaTable` or something.

**Comment by JakeGinnivan** [comment]
We just cannot break the `GetExecutedScripts` method with schema updates. I think we should spike out what it actually looks like, this might be overcomplicating things and we just have custom code which upgrades the schema table.

**Comment by dazinator** [comment]
You guys have both mentioned the delayed journalling idea! I'm a  bit wary of it because it seems like subverting how dbup works in the guise of dogfood eating - i think it would be more like eating its own niche workaround flavoured dogfood! If we bring in downgrade functionality at a later date it also complicates things as you cant really tell where the database is at if a script fails. Not saying it wouldnt work though!

Think I would rather the TableJournal implementation handle its own upgrade checking with custom code :(

Agree we need to spike!

**Comment by droyad** [comment]
Good arguments on both sides, but I think the complexity increase isn't justified just for the sake of dogfooding
