### ISSUE TITLE
MySql issue when Delimiter is the first line item

### ISSUE THREAD

**Issue by simoncuce** [DbUp/DbUp#169]
Hello

I came across an issue with MySql scripts when the delimiter keyword is the first value in the script. It would seem when the keyword Delimiter is at line 1, position 1, because the ReadCommand() tests if its a custom statement by calling the IsCustomStatement property, which in turns calls the method TryPeek. 

As a result it will always read the char + 1. So when its looking do to a comparison its trying to compare "elimiter " with "delimiter". 

The work around is to just put a space before the keyword in the script, but its not the best solution.

**Comment by MattFloyd** [comment]
I also have this dumb bug.

**Comment by simoncuce** [comment]
I fixed this in pull request https://github.com/DbUp/DbUp/pull/195/files

**Comment by phillijw** [comment]
in beta0004 there are other related issues that I can't quite describe. If you start the script with `DELIMITER ;` it seems like it tries using that as a schema or something strange. I can't explain it. Might be related to this though.

**Comment by droyad** [comment]
Above PR (195) is not for this issue

**Comment by droyad** [comment]
I had a quick look the other day, and I think the problem lies around https://github.com/DbUp/DbUp/blob/master/src/dbup-core/Support/SqlParser.cs#L289

If the thing we are looking for is the first character, index `0`, it substrings starting at `1` and ends up with `ELIMINATOR`. However if a space is added to the start, the thing we are looking for is at index `1` and it correctly substrings starting at `1`

**Comment by phillijw** [comment]
CurrentIndex should probably start off at -1 if "peek next" is going to ever work properly

**Comment by phillijw** [comment]
Stack looks like this when the problem exhibits itself:

|Name|Line|Lang|
---------|-----|-----
|dbup-core.dll!DbUp.Support.SqlParser.TryPeek(int numberOfCharacters, out string result) |Line 289	|C#
|dbup-mysql.dll!DbUp.MySql.MySqlCommandReader.IsCustomStatement.get() |Line 29	|C#
|dbup-core.dll!DbUp.Support.SqlParser.Parse() |Line 65	|C#
|dbup-core.dll!DbUp.Support.SqlCommandReader.ReadAllCommands(System.Action<string> handleCommand) |Line 60	|C#
|dbup-mysql.dll!DbUp.MySql.MySqlCommandSplitter.SplitScriptIntoCommands(string scriptContents) |Line 21	|C#
|dbup-mysql.dll!DbUp.MySql.MySqlConnectionManager.SplitScriptIntoCommands(string scriptContents) |Line 28	|C#
|dbup-tests.dll!DbUp.Tests.Support.MySql.MySqlConnectionManagerTests.ParsesOutBeginningDelimiter() |Line 69	|C#

At this point in the `IsCustomStatement` getter, the `CurrentIndex` started as 0 when it should have been -1. The reason for that is because `Read()` code, which gets called prior, is incrementing.

    public override int Read()
    {
        var result = base.Read();
        if (result != FailedRead)
        {
            currentIndex++; // <----- this is what's messing stuff up
            LastChar = CurrentChar;
            CurrentChar = (char)result;
             // We don't care about Carriage returns, unless it is followed by End of line
            if (CurrentChar == CarriageReturn && PeekChar() != EndOfLineChar)
                return Read();
            return result;
        }
        return result;
    }

**Comment by phillijw** [comment]
I think I fixed it. All tests (that I could run) have passed, plus I added a new one. Can someone please run a sanity check and run the CE test?

**Comment by droyad** [comment]
@phillijw All the tests pass (https://ci.appveyor.com/project/DbUp/dbup/build/4.0.1-PullRequest.330+2.build.393), the build runs automatically for all PRs
