### ISSUE TITLE
Integration tests on appveyor?

### ISSUE THREAD

**Issue by omnibs** [DbUp/DbUp#177]
I've seen [appveyor supports testing against rdbms](https://www.appveyor.com/docs/services-databases).

I think I've seen we only do diffs on recorded sql commands as a means of testing dbs other than Sqlite.

What do you think about integration tests against real DBs on appveyor? 

The Cons is we'd lose the ability to run the entire test suite on local machines unless we have all the dbs installed, but I think after 4.0 we could talk about splitting up the repo (like [LightInect](http://www.lightinject.net/) does) with a dumber main repo and db-specific repos for each supported technology. We've been holding the Oracle guys back, but with this topology they could be maintainers of the DbUp.Oracle NuGet.

**Comment by JakeGinnivan** [comment]
I think thats a good idea, I think we should add a DbUp.SmokeTests which has a single smoketest for each database that DbUp supports. It would add a lot of confidence.

I don't think the test project should take this approach because that will make it really hard to run tests locally.

Finally, I don't think we should split up the repo yet. Maybe we can think about that after v4 is released. The issue with Oracle is that it conflates adding Oracle support with adding two major features to DbUp.
If the features were added by themselves before Oracle support was added then it wouldn't really be an issue.

**Comment by sungam3r** [comment]
CI was migrated to GitHub Actions.
