### ISSUE TITLE
WithTransaction and MyJournal

### ISSUE THREAD

**Issue by vvklymchuk** [DbUp/DbUp#196]
Hi
I use my own class MyJournal (a table in MSSQL) and WithTransaction in my setup.
When I execute three scripts with an error in the third script for example, the transaction rolled back successfully. But first and second scripts are logged into the journal table. If I understand correctly these scripts shouldn't be logged to the table.
Please help.

**Comment by droyad** [comment]
I'm guessing you are using the `JournalTo` method. Since this does not provide you with the `IConnectionManager` you are most likely creating your own connection connection and hence not participating in the same transaction.

I've added an overload to `JournalTo` that will supply the `IConnectionManager`.
