### ISSUE TITLE
 DbUp for updates to more than one database

### ISSUE THREAD

**Issue by rashmi-shastri** [DbUp/DbUp#199]
I am using DbUp and works fantastic when using one DB and one console application. Using scripts targeting multiple databases in one console app did not work well or I did not set it up correctly. How do you propose to use DbUp when multiple DBs are in play?

Thanks, 
Rashmi

**Comment by AdrianJSClark** [comment]
Instead of building a single upgrader instance I would build one for each target database. Then, while configuring each upgrader, you should pass an appropriate filter to your chosen script provider. Or, if a suitable provider with a filter option does not exist, implement a custom script provider that includes a filter method. That way each upgrader will only see the scripts appropriate for a single database and can then be used to upgrade just that database.

For example, if you were using scripts embedded in your assembly, I would place the files in separate folders with one folder for each target database. Then I would pass something like `name => name.StartsWith("MyAssembly.Scripts.DbNameFolder.")` as the second parameter to the `WithScriptsEmbeddedInAssembly(...)` method call. The "DbNameFolder" part obviously would change for each database (and the rest would change depending on the embedded resource names you had).

Feel free to ask further questions if I'm not being clear enough.

**Comment by JakeGinnivan** [comment]
I assume this has been resolves, please let us know if it hasn't

**Comment by alexandermlharris** [comment]
> What would be the advice, if you had 2 db's with order dependency upgrades.
> i.e. a set of scripts that required to run in this order (due to cross database queries being run in script2 that access db1/db2)
> 
> * DB1-->Script001
> * DB2 -->Script002
> * DB1 --> Script003

This is exactly the situation that we find with our internal systems. Made more complicated by having one "external" (to our team) database which we don't develop oursleves yet for which the interfaces is to select / use objects directly from that DB since it is co-located on the same DB server.

I don't really see a clean way around this issue - beyond "it's bad practice - don't do it" which doesn't help in the here and now.

One workaround is if you can organise your dependencies (or they are already that way) such that they always point one way. ie: if DB1 -Depends on-> DB2  (for example, DB1.view which selects from DB2.table), then you can always release a change to DB2, then a release to DB1 that updates the objects which depend on DB2.

This isn't pretty however and even in this case, you have a breaking issue when trying to migrate a blank or old database to the current schema.

If the dependant database isn't at the same point in time as well, and updates in lockstep you will likely run into issues.

For example:

**0, Initial state**
* SharedDB
* AppDB

**1. Shared DB change*
* SharedDB adds a table named X.

**2. App DB State Changed**
* AppDB updated to depend on X.

**3. Shared DB State Changed**
* SharedDB renames table to Y.

**4. App DB State Changed**
* AppDB updated to depend to Y.

Now, some time later... I want to update an older devlopment copy of AppDB from state 1. OR I want 
I want to spin up a fresh local isntance of AppDB for testing / developing.

* If I run DbUp vs my AppDB (old or empty), it's at some point going to execute script 2.
* This migration will try to add an object which depends on X.
* X doesn't exist in SharedDB because it's now called Y.
* Process fails.

If anyone has experiance working in scenarios like this I'd be really interested in hearing about it. as I said "don't do this" might be the "best" advice in archetectural terms... but doesn't help work around this now!

Any thoughts MUCH appreciated.

**Comment by rupoase** [comment]
@rashmi-shastri , while I haven't tried it yet, I might need to in a very near future....
My strategy is to provide a json file that would get updated with each connection string for each database and run a for-each loop on the updater. I'd have to implement a simple JSON parser and that's pretty much it.

In my use case the databases need to be exactly the same, so all the scripts need to run for each database that is found in the connection string.
