### ISSUE TITLE
Transaction strategy not configurable per script

### ISSUE THREAD

**Issue by timhenstridge** [DbUp/DbUp#207]
I have an issue where I want to run most scripts inside dbup's per script transaction strategy but some SQL statements simply cannot be run inside a transaction such as CREATE FULLTEXT and ALTER DATABASE, 

I tried injecting my own ITransactionStrategy but can't seem to set this due to class access and how the library was written, I also looked into dynamically altering the "TransactionMode" to no success. what I really want is a per script setting/rule that says "No Transaction" which can pass along, are there any ideas?

So far my solution to achieve this will be to create 2 upgrade engines one with per script transactions and one with no transactions and run each engine but this will not ensure a single sequential path of updates.

**Comment by JakeGinnivan** [comment]
I think the only solution is to let the scripts deal with the transaction themselves and set DbUp's transaction mode to no transaction.

Otherwise what would the API look like? Also, if you set a script to no transaction and also said to put a transaction around everything, would you throw when trying to build the engine?

Happy to get a PR if you can come up with a nice way to add this in.

**Comment by jineshk** [comment]
One work around, that I have used is to 

1. Disable transaction at builder level
2. Hook into Script preprocessor which is called per script
3. Wrap sql content (string) in transaction conditionally

Not completely elegant but does the job.

**Comment by rahulpnath** [comment]
Hit the same problem and ended up doing something as suggested above. More details [here](https://rahulpnath.com/blog/exclude-certain-scripts-from-transaction-when-using-dbup) for anyone interested
