### ISSUE TITLE
Question: Is it possible to rollback a deployment?

### ISSUE THREAD

**Issue by RobMalvern** [DbUp/DbUp#238]
In my case the deployment of the database would be via Octopus Deploy.

Say Database 1.7.0 gets deployed, with scripts 0001 to 0010.
Then a bug in script 0010 is discovered in production, so Database 1.6.0 is re-deployed (with scripts 0001 to 0009).
As far as I can work see, this won't perform a roll back because the SchemaVersions table will contain 0010, is this true?
I assume the way to roll back would be to create Database 1.8.0 with script 0011 being an "undo" script for script 0010.
Am I correct in this assumption?

Is there any way to make a roll back like this work? From my understanding there isn't, but I've only looked through the documentation for half an hour 😉

**Comment by hossambarakat** [comment]
Hey @RobMalvern, 
Your assumption is correct, You need to think about rolling back an old script by rolling forward another script.

**Comment by dazinator** [comment]
Rolling forward is preferred. However rollback scripts are supported and there are ways to achieve what you want. Basically what you want to do is, before you deploy the previous version, you want to run the rollback method using the current version that's deployed - as the current version is the one that has the actual roll back script. 

E.g 

1. Deploy version 9 (which updates dB to version 9 but also has rollback script to undo changes)
2. Execute version 9 in rollback mode.
3. Deploy version 8 using octopus.


Another way to do it, is rather than using embedded scripts, you can deploy your scripts to a folder on disk, and use the file based provider in dB up. This means I. The above scenario, when you deploy the old version, it will still have access to all of the latest scripts. So in that scenario you can deploy an old version using octopus and add some logic to run the rollback scripts if it detects it's an old version being deleted over the top of the newer one.

**Comment by hossambarakat** [comment]
I'd like to recomment reading this thread https://github.com/DbUp/DbUp/issues/42

**Comment by RobMalvern** [comment]
Thanks for your answers!
It certainly looks like it's worth me investigating DbUp further for my application. If I have any more comments or questions I'll add them to the thread you've linked.
