### ISSUE TITLE
Powershell DB create

### ISSUE THREAD

**Issue by jisheedpdm** [DbUp/DbUp#263]
Is there any way to create a database using script in powershell??
I'm using the following powershell commands

$databaseName = "My_DB"
$databaseServer = "MyServer,1558\SQLEXPRESS" 

$scriptPath ='My script path'
Add-Type -Path 'D:\\Myproject\packages\dbup.3.3.5\lib\net35\DbUp.dll'

$dbUp = [DbUp.DeployChanges]::To
$dbUp = [SqlServerExtensions]::SqlDatabase($dbUp, "server=$databaseServer;database=$databaseName;Trusted_Connection=Yes;Connection Timeout=120;")
$dbUp = [StandardExtensions]::WithScriptsFromFileSystem($dbUp, $scriptPath)
$dbUp = [StandardExtensions]::LogToConsole($dbUp)
$dbUp = [StandardExtensions]::WithTransactionPerScript($dbUp)
$upgradeResult = $dbUp.Build().PerformUpgrade()

** The script path contains 3 scripts - to create the database, tables and everything.
But actually I have to create the specified "My_DB" database using the script in the script path.
Now jenkins throws an error like "Cannot open database " since it is not yet created, I tried by specifying the master database but still the database is not creating. If we manually execute only the database creating script in server then the rest of the scripts will run through jenkins.

So guyz is there any way to create the database using a script in powershell??? 
@aggieben @teyc @FilipDeVos @stephengodbold

**Comment by AdrianJSClark** [comment]
Attempting to create a database during an upgrade can be tricky. It sounds like your code is attempting to connect to your target database before you've had a chance to create it. The reason for this in the code sample you've provided would definitely be because you are using your target database name in the connection string. If you also get that error when specifying `master` then you may need to examine your scripts for `USE` statements or database prefixes.

I've found that it is best to create your database outside your normal upgrade scripts. The simplest way might be to use the built-in DbUp `EnsureDatabase` method.

In C# this call is:
```csharp
    // Construct your own connection string here of course
    var connectionString = "Server=(local)\\SqlExpress; Database=MyApp; Trusted_connection=true";
    EnsureDatabase.For.SqlDatabase(connectionString);
    // Continue to use the connectionString with a normal "DeployChanges.To" built upgrader
```
Translating to PowerShell I'd imagine you could do:
```powershell
    $connectionString = 'Server=(local)\\SqlExpress; Database=MyApp; Trusted_connection=true'
    [SqlServerExtensions]::SqlDatabase([DbUp.EnsureDatabase]::For, $connectionString)
```

Your situation might be more complicated, however. For example, you may need to grant certain permissions on database creation. In this case you would need to script the database creation step and run it using a separate upgrader instance. When creating this instance the connection string would be made so that you connected  to the `master` database instead of your application database. Once the database creation upgrader instance has executed successfully, you can continue with your normal upgrade scripts.

Normally when I make use of DbUp I'll wrap it within a small console application. This makes it quite simple to use from all scripting environments, including PowerShell. There's an [example of such an application called "DbUp.Console" in the repository](https://github.com/DbUp/DbUp/tree/master/src/DbUp.Console).

**Comment by teyc** [comment]
This might work...
```
Import-Module .\DbUp.dll
$myConnectionString = "Server=.\SQLEXRESS;Database=SampleDb;Trusted_Connection=Yes"
[SqlServerExtensions]::SqlDatabase([DbUp.EnsureDatabase]::For, $myConnectionString)
```

**Comment by jisheedpdm** [comment]
@AdrianJSClark @teyc 

Thanks guys.. It's working for me..

**Comment by nitinjain1005** [comment]
@jisheedpdm  @AdrianJSClark   .. Could you please share you steps which can be followed for run dbup dll from Powershell script... As In my TFS pipeline we are restrict to use only Powerscript...

I download dbup master  (https://github.com/DbUp/DbUp) and giving path of bin folder (DbUp-master\src\Samples\SampleApplication\bin\Debug\netcoreapp2.0\dbup-core.dll)

I am getting below error message :


Cannot find an overload for "SqlDatabase" and the argument count: "2".
At line:8 char:1
+ $dbUp = [SqlServerExtensions]::SqlDatabase($dbUp, "server=$databaseServer;databa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
 

Could you please assist me by sharing steps or help on error message.

**Comment by teyc** [comment]
@nitinjain1005 Try the sample here and let me know if it works https://github.com/teyc/DbUp/tree/samples/powershell/src/Samples/PowershellSampleApplication
