### ISSUE TITLE
DbUp in concurrent processes

### ISSUE THREAD

**Issue by wahabakhtar** [DbUp/DbUp#349]
We have multiple binaries/processes that references the same backend database for load-balancing, went through the documentation but didn't find much information on any best practices for updating database in concurrent environment.

Does anyone have experienced such issues in production environment?

**Comment by droyad** [comment]
This question is not specific to DbUp, and would be the same for all update tools. Tt is better suited for a Q&A site like StackExchange.

**Comment by mookid8000** [comment]
I know it's an old issue, but here's just for future people Bingling for this type of info (which just happened to do): 

Database migration libraries can (and should IMO) address this somehow, which my own little [migr8](https://github.com/rebus-org/migr8) does (and has done since its inception ~10 years ago) – as described [here](https://github.com/rebus-org/migr8#transactions-locking-and-such), migr8 will start a db transaction with isolation level SERIALIZABLE, insert its migration log entry into its migration log table (which effectively works as a global lock on the database with respect to executing further migrations), execute its migration, and then commit. This way, concurrently running processes will most likely take turns executing migrations, until the database has been fully migrated.

Another thing that migr8 handles (which I haven't seen addressed in any other database migration library), is the problem of _adding migrations on feature branches_ – it uses its [branch specification](https://github.com/rebus-org/migr8#branch-specifications) concept for that, allowing for development teams to add migrations without a global, real-world exclusive lock on the migration number sequence.
