### ISSUE TITLE
How to execute sql files in other class Libraries (modules)

### ISSUE THREAD

**Issue by AliAfsharii** [DbUp/DbUp#377]
Hi
We have a modular .net core project and we want to put the migration files of each module(class library) in itself so when we use one of modules in another project, it has its migration files.
How can it be done?

**Comment by dazinator** [comment]
DbUp can run scripts in assemblies. If your system is modular i am assuming it can get access to each "module" assembly yes? On startup of your app (or at module install time) get the module assemblies and then loop through them and run a dbup migration from that assembly. Another option is to write a custom IScriptProvider that provides the scripts registered by your modules, then you can run dbup once with your custom IScriptProvider and it will run any migrations from any of your modules rather than having to repeat it per assembly as a time.

**Comment by AliAfsharii** [comment]
It's done. It only needs to get assembly reference to WithScriptsEmbeddedInAssembly in builder. for multiple assembly it need to call function multiple times with different assemblies.

var anotherAssembly = typeof(ClassLibrary1.Class1).Assembly;
.
.
.WithScriptsEmbeddedInAssembly(anotherAssembly)
.WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())

but still there is q question. we load assemblies from config file by name and count of loaded assemblies may be differ. how can I handle multiple assemblies count at runtime?

**Comment by AliAfsharii** [comment]
I use WithScriptsEmbeddedInAssemblies instead of WithScriptsEmbeddedInAssembly to run sql files in multiple assemblies
