### ISSUE TITLE
HOWTO Question: environment-specific execution

### ISSUE THREAD

**Issue by brettveenstra** [DbUp/DbUp#412]
Is there a current feature or pattern one should use when scripts need to be applied only in certain scenarios/environments?

Looking for a way to specifically opt-in to script execution but keep in source control as part of "normal" sequence of scripts.

**Comment by alexandermlharris** [comment]
Disclaimer - I'm just looking into DbUp myself for possible work adoption so I'm a beginner, but I'd been considering approaches to this.

My insiration comes from some of the samples in the repository and I'd considered how you configure the builder's included scripts (and script filters).

Since YOU basically write and configure the app that's DOING the deployment processing you can control the scripts that are included... so, for example you could do something like:

* Pipe in a command line argument specifying the environment
* Switch in the code to change which `.WithScripts` directives you use, or to control thier filters
* Use this to include / exclude folders or scripts named by convention based on the environment name

Something like...

`.WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly(), script => script.StartsWith("MyProject.QA")`

**Comment by jburger** [comment]
I think @alexandermlharris is spot on. 

There is an example of how to use command line arguments to control deployment here in the [Samples](https://github.com/DbUp/DbUp/blob/afcc42ef980ff7b81e4e372192ecb496e8797fe3/src/Samples/SampleApplication/Program.cs#L38) too.

I'm going to close this one as answered, but feel free to re-open if you need further clarification.
