### ISSUE TITLE
Downgrade functionality

### ISSUE THREAD

**Issue by Lars-Kolsaker** [DbUp/DbUp#42]
Hi
Great product!

Any plans on implementing functionality for setting the database back to a previous version.

**Comment by dazinator** [comment]
I'd love to see a "target version" concept in DbUp. At the moment there is no concept of database version really, just script names - which you explicitly tell dbup the scripts to run. The database  "version" is simply the name of the last script that was run and recorded in the schema versions table. I'd like instead to tell DbUp the target version number I want to migrate the DB to, and let it decide which scripts are necessary to execute to take the database to that version.

One rudimentary way to outline this idea, imagine creating a subfolder in the projects scripts folder per version of the DB, and putting a single script + rollback script in that folder:

    - 1.0.0
        - addedtable.sql
        - addedtable-rollback.sql
    - 1.0.1
        - addedcolumn.sql
        - addedcolumn-rollback.sql

You could then ask DbUp to migrate the DB to a partiular version:

```
.ToTargetVersion("1.0.1")
```

Which would result in all of the upgrade (or rollback) scripts being run to take the DB to that version.

**Comment by rickculpepper** [comment]
> I'd love to see a "target version" concept in DbUp. At the moment there is no concept of database version really.... I'd like... to tell DbUp the target version number I want to migrate the DB to, and let it decide which scripts are necessary to execute to take the database to that version. 
> --snip---

This would be a useful feature. 

> One... way to... [do this is by] creating a subfolder in the projects scripts folder per version of the DB, and putting a single script + rollback script in that folder....
> 
> --snip--
> You could then ask DbUp to migrate the DB to a partiular version:
> 
> '.ToTargetVersion("1.0.1")'

I like the concept here, though it seems the idea of a single upgrade script and a single rollback script per folder might be limiting. On the other hand, it make the upgrade process very granular, which I like. If you are limiting to one upgrade and one rollback script per folder, then why not mandate the names 'upgrade.sql' and 'rollback.sql'? Hmmm... this idea might not be well-throught-through... ;)

It seems to me that the upgrade side of this can already be done with DbUp using a filter on folders of scripts.

**Comment by JakeGinnivan** [comment]
I don't think we should invent our own separators inside sql files. I think we should try to stick to features already in DbUp to do this.

The way I would do it:

1. Add `.WithRollbackScriptConvention("_rollback")`, we could use optional parameters to fill in the default
1. Add `.PerformDowngrade(target)` on the `UpgradeEngine`
1. Introduce an overload to `.PerformUpgrade()` which takes the `target` argument
  - `target` is a string, for upgrade it will run scripts until the target is passed (it is inclusive). I think the logic should be something like `scriptName.StartsWith(target) || scriptName <= target` (obviously need tests around this filter
  - For downgrade it would run _rollback (or scripts matching convention) in reverse order until it hits the target. This would be exclusive rather than inclusive. So the logic would be `!scriptName.StartsWith(target) && scriptName > target`

This would be a completely backwards compatible change as everything is opt in, and it is not overly complex. It also allows everyone to use this feature, as it is not tied to naming scripts in a particular way.

**Comment by dazinator** [comment]
@JakeGinnivan so just thinking of how this would tie in with an octopus deployment process. 
If we deploy octopus release 1.0.0 with dbup console app 1.0.0 - it creates / rolls up the database. We then deploy release 1.0.1 with dbup console package 1.0.1 which has a new script in so it rolls up the database. Now we want to revert back to version 1.0.0 for some reason and we dont want to lose data so would rather run rollback scripts than restore. So in this scenario we can't just deploy release 1.0.0 from octopus again as that older package won't have the required rollback script in (a problem you raised before). It would be nice if we could work this way though and perhaps there is something fancy people could do in their console app to allow this workflow like storing the rollback scripts in a global directory so that they are available for the older app. But failing that, running the dbup rollback procedure would be run seperately just prior to the octopus deployment procedure for the old release - which works too but not quite as nice.

**Comment by dazinator** [comment]
Further to above, what if dbup stored the rollback scripts in the database itself.. that way an older version of the console app could automatically detect a greater version of the database and have the scripts neceasary to execute a rollback..

**Comment by JakeGinnivan** [comment]
Nice idea, that could work well

**Comment by DamianMac** [comment]
My 2c

It's horrible horrible idea. The reason migrations work (particularly with deployment automation like Octopus) is that by the time you get to prod, your migrations have been rehearsed a bunch of times. So you can be pretty sure that they're going to work.

The same can't be said for roll back scripts. You've just not "rehearsed" them. 

Secondly, the only reason a migration script will fail is if your target DB isn't in the state that you expect it to be in. So at that point, thinking you can rely on an already written, but untested backout script is asking for all sorts of trouble. That trouble will take the shape of unintended, un-traceable data loss. If you have a migration fail today, you'd have to examine it, figure out why it broke, write a script to fix it, and figure out how to get to where you want to go. After that, you'll look at your process so it doesn't happen again. 

If you blindly ran a backout script instead you're likely to make even more of a mess.

**Comment by JakeGinnivan** [comment]
That was my original thoughts, but the scenario that you fought for was when you deploy to prod, and find a bug in your code and you want to deploy and old version and go back. For failed migrations, the only way is forward or restore backup. But those are all manual intervention.

The only scenario where the rollback scripts would be employed would be when there are code bugs, and it would take too long to get a new release ready. In that case you are optimising for safety and the ability to roll back rather than time to fix. If you are creating _rollback.sql scripts, part of your testing should be upgrade, downgrade then upgrade again for your pre-prod environment.

**Comment by dazinator** [comment]
@JakeGinnivan that makes sense to me. I think we are all advocates of the always roll forward approach, but I can see that it is also possible for a team to write well tested rollback scripts, and therefore - for those teams who need this feature and employ it responsibly, there is value. We should just wrap it in appropriate disclaimers though - basically everything @DamianMac has said maybe.

**Comment by SleeperSmith** [comment]
@JakeGinnivan and that is exactly what we do with Entity Framework.

We make a full upgrade, downgrade 2x + upgrade again on every commit. Call me old school but I still refuse to deploy change scripts without rollback scripts. I don't see anything wrong with this?

**Comment by JakeGinnivan** [comment]
@SleeperSmith as long as DbUp has disclaimers around the approach I don't mind it being in there, we do need to make changes to the schema version table which we don't have a way to do that yet so we can store the scripts. We also need to maintain compatibility (unless we put into v4 as a small breaking change to the API's).

Though I won't be personally spending time implementing this, at least not until I clear the pull request backlog. If someone wants to put up a pull request to push this forward then great!

**Comment by omnibs** [comment]
Can we have this tagged as up-for-grabs to increase the chance anyone with enough time on their hands stumbles upon it?

**Comment by shiranGinige** [comment]
I started working on this today. The approach is as follows. 

1. A new column **BatchNumber** is added to the **SchemaVersions** table 
2. When **UpgradeEngine.PerformUpgrade** is called, it will look for the current max value of the **BatchNumber** and increment it by 1 and that save scripts of the current batch with the new BatchNumber 
3. New method *UpgradeEngine.PerformDowngrade(int batchNumber)* will perform a look up of all scripts added under that batchNumber and check for related *RollBack Scripts* 
  - for example .. 
   If *Script0006 - Transactions.sql* supports rollback a matching *Script0006 - Transactions_rollback.sql* need to be added to the Scripts directory ( if wanted this can be changed to a seperate RollbackScripts directory but I preferred to keep it alongside the original file for clarity)
4. The rollback scripts are executed on the descending order and the original entry in the **SchemaVersions** is updated  with **rolledback_Script0006 - Transactions.sql**

Fork : https://github.com/shiranGinige/DbUp

Note : Only implemented this for **SqlTableJournal**  and if the approach is ok I can have a look at extending it to other Journals. 

Let me know what you guys think ?

**Comment by dazinator** [comment]
@shiranGinige - cool stuff!
I think this is great, but something I think could make it greater would be if we could find a way to change `batchNumber` `int` to a `Version` number, so people can more easily correlate this with releases. For example:

```
var targetVersion = Version.Parse("1.0.1");
UgradeEngine.PerformDowngrade(targetVersion);
```

That way the version could be passed through from tools like octopus deploy (the current release version being deployed) or read from the assembly version attribute at runtime (if you set this) and also inspecting the schema versions table you can more easily correlate to a release.

I guess for this to work though, there would need to be a way to capture what the present version number was when doing a `UpgradeEngine.PerformUpgrade()`. At the moment it can calculate the next batch number easily via a lookup, but with the version number suggestion you'd probably need to supply the current version number that executed scripts should be stored as..

What are your thoughts on this?

Oh lastly, we toyed with the idea of storing new rollback script contents in the actual database whenever an upgrade is performed rather than on disk, so that when you deploy the older version, the rollback scrips could be looked up from the database and executed - is that a route you would consider with the Pr as i think that would be more awesome!

**Comment by clauchiorean** [comment]
Hi,

What is the status of this functionality?

**Comment by Jason-Freeosk** [comment]
Hello,

If anyone is still watching this thread, I have a question.

This thread is in regards to rolling back a **production** deployment. For a production environment, I agree that you go forward - fix the bug and deploy the fixed version.

How has anyone handled this in a **development** environment where the databases are separate per developer? If there is a reason I or other developers need to revert our development database back to a previous version, how have you accomplished this?

If there is another place where this question is answered, please let me know.

Thank you!

**Comment by dazinator** [comment]
Are the databases running in the developers local environment?
Typically we would add a script to source control, and as developers pull the latest, and run DbUp console project locally, it would apply the new script to their local database. i.e no different than the normal roll forward approach, its just the scripts are running on the local developers box.

**Comment by Jason-Freeosk** [comment]
Correct. The db's are local to the developer. So for example, on our dev machine we may need to rollback our app from v2 to v1. When doing so we also need to revert the database to a matching version. So v1 only has the update scripts, if any, for v1. There won't be any revert scripts that remove v2 code in v1. Does that make sense? If so, in that scenario how do you manage reverting the database from v2 to v1?

**Comment by dazinator** [comment]
If you do have revert scripts, v2 would have them. When you rollback the app to v1 you would need to do it using v2. Then revert the app itself after the db rollback has completed

**Comment by keithn** [comment]
@dazinator is your seed data conditional on being in the development environment? if so, how did you handle that?

**Comment by nvarscar** [comment]
Hi all,
I'm really looking forward to any possible way of rolling back a deployment. So far, the only work around is using ad-hoc queries that perform the rollbacks and then remove entries from the SchemaVersions table, but I'm concerned about transactionality of such approach, as well as about multiple other things, like, how to store rollback progress in case it fails, for example.
Here are some of the solutions I have in mind: 
1. Store rollbacks in a different table - maybe with a postfix '_rollback'. The regular deployment scenario should then check against both tables whether the script was not rolled back (probably, using deployed dates) - some additional code behind the scenes. 
2. Have an additional column in SchemaVersions that shows the status of the script deployment: deployment started, deployed successfully, rolled back, is rollback(?). This seems to be the easiest approach so far, but will require 1 to 1 mapping between deployment script and rollback script.
3. Provide an interface for users to remove entries from SchemaVersions. Rollbacks will be then treated as regular deployments that leave entries in SchemaVersions, but use different script names. Previous successful deployments will be wiped from the deployment history.
4. Some amalgamation of 2 and 3, where users control the rollback status for each script, as well as use SchemaVersion for rollback logging, with rollbacks having different naming (for obvious reasons). This might work as something like this:

```powershell
$dbUp = [DbUp.DeployChanges]::To
...
$scripts = @([DbUp.Engine.SqlScript]::new('ScriptThatIsBeingRolledBack.sql','<some code here>'))
$scripts += [DbUp.Engine.SqlScript]::new('OtherScriptThatIsBeingRolledBack.sql','<some code here>')
$rbScripts = [DbUp.Engine.SqlScript]::new('MyRollbackScenario.sql','<rollback code here>')
$dbUp = [StandardExtensions]::WithRollback($dbUp, $scripts, $rbScripts)
$dbUp.Build().PerformRollback()
```
That way, the engine would know which scripts to rollback and how to store the progress.

So far my favorite option would be 4, as it provides greatest flexibility, yet still operates within a DbUp framework.

**Comment by nvarscar** [comment]
@keithn that seems to be a good solution at first, but unfortunately, becoming much more inconvenient when trying to implement. Fixed scripts would have to have different names, otherwise second deployment attempt would deploy nothing due to journalling. Same set of scripts (if used from a folder, let's say) would go through rollback unnecessarily every time the scripts are deployed into a new database, meaning that rollback scripts and the original faulty should be removed from the source, but only once they are deployed, which also introduces disconnect between what was actually deployed and what is there in the source.
Even though everything in the database is deployed as migration forward, in its current state it means a lot of manual activities, which defies the purpose of the project - automatic deployments. Proposed solution, while not ideal, at least gives us some control over the rollback process.

**Comment by asimeonov** [comment]
I have exactly the same issues as you all. I love the idea for 'rollback as a migration forward' and I totally agree that this is the correct approach. However in our company when app is failing you don't want to search a developer to fix the current version while the new nor previews are working. So I created a simple solution that plug into the DbUp pipeline, adds support for rollback / downgrade scripts, stores them in SchemaVersion folder and automatically performs downgrade if older version is detected. 
The solution is far from perfect and this is why I'm writing this message, any feedback and support will be appreciated. Also my code supports only sql server for now, I'll add all supported DbUp engines after I gather some feedback over the solution. You can find it here https://github.com/asimeonov/DbUp.Rollback/ also I have published a preview package in nuget https://www.nuget.org/packages/DbUp.Rollback/

**Comment by mjauernig** [comment]
With the existing extension https://www.nuget.org/packages/DbUp.Downgrade/ i would close this issue. Something against it? 

In the docsi would link the project. Thank you for creating the extension @asimeonov.
