### ISSUE TITLE
RFC: Drop Older Framework Support

### ISSUE THREAD

**Issue by AdrianJSClark** [DbUp/DbUp#432]
I noticed that @droyad is talking about a 5.0 release. In the lead up to that release I wanted to ask if we wanted to use that as an opportunity to leave behind some of our older framework dependencies?

As an example, `dbup-core` supports these frameworks:
```netstandard1.3;net35;net45;netstandard2.0```

My preference would be to simply support `netstandard2.0`. This probably isn't realistic for the wider audience. Considering the currently-supported frameworks, we probably should include .NET Framework 4.5.2 (4.5 and 4.5.1 are out of support) giving this as the target frameworks:
```net452;netstandard2.0```

Obviously this is just one library as an example, there would need to be some thought put in across the board.

**Comment by AdrianJSClark** [comment]
Guidance from Microsoft on this topic for reference [Cross-platform targeting - Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)

**Comment by justinjstark** [comment]
dbup-sqlserver now requires .NET framework 4.6 to get AppAuthentication support. So if you support 4.5 you're going to need an additional target for 4.6 in that project. Why not make the minimum .NET framework 4.6?

**Comment by AdrianJSClark** [comment]
@justinjstark I'd have no problems with going higher personally. I'd like this to be an opportunity to push things as far into the future as possible, without making DbUp unusable for too many people.

Setting support level based on individual DB support requirements, such as your example of SQL Server "AppAuthentication" support, is something which would be easier if each database technology was more separate as discussed in #431. That way `dbup-core` could be the absolute base level of support however the DB providers like `dbup-sqlserver` would be free to decide on a higher minimum if that was warranted to ensure a particular feature.

You closed #431 @droyad, is splitting things up still in the plans?

**Comment by AdrianJSClark** [comment]
I just wanted to leave this blog post here as extra fodder for those following this issue to chew over.

[.NET Core, .NET 5; the exodus of .NET Framework?](https://blog.marcgravell.com/2020/01/net-core-net-5-exodus-of-net-framework.html)

**Comment by jafin** [comment]
Any movement from 2020?

Motivation to move to netstandard2.0   (or at least fork a v5.x to netstandard2.0)

* SQLite (and possibly other) libraries only support netstandard2.0 in recent versions.  There are bugs that get fixed by levelling up.

If supporting legacy is a priority, any objection to branch to a major rev (5.x?) at a netstandard 2.0 level?  and just back port any important changes to the existing 4.x line.

**Comment by dazinator** [comment]
> Any movement from 2020?
> 
> Motivation to move to netstandard2.0 (or at least fork a v5.x to netstandard2.0)
> 
> * SQLite (and possibly other) libraries only support netstandard2.0 in recent versions.  There are bugs that get fixed by levelling up.
> 
> If supporting legacy is a priority, any objection to branch to a major rev (5.x?) at a netstandard 2.0 level? and just back port any important changes to the existing 4.x line.

There is the core dbup project and then there are database specific provider projects for example sql server, sqlite etc. Just pointing out that providers can be bumped independently of the core, so to keep sqlite in support only the sqlite project would need to be bumped to netstandard2.0 initially..

**Comment by jafin** [comment]
Thanks @dazinator  for the response.

In regard to the database specific providers.

I may have it wrong, but when I attempted to level up the MySQL library to later dependencies and target netstandard2.0; the tests in dbup-tests would no longer compile. 

```
Error NU1201: Project dbup-sqlite is not compatible with net46 (.NETFramework,Version=v4.6). 
Project dbup-sqlite supports: netstandard2.0 (.NETStandard,Version=v2.0)
```

Perhaps there is a way to resolve this issue, separating the MySQL test (and other vendor tests) into their own test assemblies?

In regard to levelling up,  I can see my statement doesn't hold enough weight to warrant a serious debate.

This project does a good job of supporting frameworks even Microsoft no longer maintain, if that is a goal then I can see why there is pause on progressing the minimum framework.

I'm not really adding to anything that hasn't been discussed above in relation to support of Xamarin SQLCE etc. If there is a large userbase that demand this then I see reason.

It can sometimes be challenging to refactor code with numerous `#if Defs.`,   By increasing the framework level, it could minimize the requirement for so many of these, keeping the code simpler, which perhaps ideally can reduce bugs.  But this is all hypothetical.

To my suggestion about branching, if the code is branched, and the 4.x remains to support these versions and backport any required changes, and then tip runs netstandard2.0.  Thereby 4.x continues to provide support for these platforms while offering opportunities to progress on more current platforms.  Are there challenges with doing this? Perhaps the CI/CD is awkward?

**Comment by dazinator** [comment]
> To my suggestion about branching, if the code is branched, and the 4.x remains to support these versions and backport any required changes, and then tip runs netstandard2.0. Thereby 4.x continues to provide support for these platforms while offering opportunities to progress on more current platforms. Are there challenges with doing this? Perhaps the CI/CD is awkward?

If it was decided to discontinue support for older platform targets, I'd agree that keeping a branch around for reference purposes (or critical fixes someone would like to make etc) would be courteous.

> I'm not really adding to anything that hasn't been discussed above in relation to support of Xamarin SQLCE etc. If there is a large userbase that demand this then I see reason.

> It can sometimes be challenging to refactor code with numerous #if Defs., By increasing the framework level, it could minimize the requirement for so many of these, keeping the code simpler, which perhaps ideally can reduce bugs. But this is all hypothetical.

I agree with your thinking. It's a bit of a tradeoff. If legacy platforms aren't being used and the overhead / increased complexity of supporting them is great, then I agree it makes sense to drop support for them. 

I did a quick check and found that, not including `LibLog.cs` there were a total of 10 different compilation constants used, via `33` `#if`'s, spanning 23 files. The constants are:

```
SUPPORTS_LIBLOG
USE_TYPE_INFO
MY_SQL_DATA_6_9_5
NPGSQLv2
MONO
NETCORE
SUPPORTS_AZURE_AD
SUPPORTS_SQL_CONTEXT
LINQ
TEST
```

Perhaps it might make sense to open up an issue focusing on a specific constant (or set of constants) from the above list, where it's felt that they are adding a sufficient complexity cost, and describing why it doesn't make sense to keep them, and what the impact of removing them would be - for example levelling up a providers baseline to netstandard 2.0 etc. This could then be done in a more gradual way that slowly evolves the code base or individual providers with granular PR's, and possibly, eventually the core, rather than a big bang PR.

**Comment by DavidJohnWilliams** [comment]
[Support for anything before 4.6.2 has ended.](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/)
[.Net Standard 2.0 is supported for anything 4.6.2 or above.](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#select-net-standard-version)

So it would be quite reasonable IMHO to drop support for anything except .Net Standard 2.0. It is pretty easy to also add support for .Net6.0+ with multi targeting, but there is really only a need to do so if you need/want to use something specific from .Net.

And contrary to some comments above, .Net Standard is not going to be going anywhere for a while because it is and will remain the bridge between .Net and .Net Framework. Until .Net Framework is completely dropped supporting .Net Standard is very reasonable unless there is a really good reason not to.

**Comment by droyad** [comment]
What @AdrianJSClark said

> .Net Standard is not going to be going anywhere

I suspect it'll be a long time because it's just an API spec not a runtime and .NET has been _really_ good at being backwards compatible.

We'll most likely have to follow the lead of our dependencies (e.g. `Microsoft.Data.SqlClient`) on what the min framework is.

**Comment by jburger** [comment]
This change and the choices that @AdrianJSClark and @droyad explain in the RFC and comments above make sense for me, supporting old frameworks forever is not practical, and this is a good time to make the move. :+1: from me

**Comment by dazinator** [comment]
Agreed now is a good time

**Comment by sungam3r** [comment]
Covered by #655.
