### ISSUE TITLE
[DbUp-Core] SQLParser fails to parse some nested block comments

### ISSUE THREAD

**Issue by jarnoj** [DbUp/DbUp#439]
this fails (no space between end block comment chars):
`/* comment1 /* comment2 */*/`

this don't:
`/* comment1 /* comment2 */ */`

**Comment by AdrianJSClark** [comment]
Hi @jarnoj!

Thanks for lodging this. I will have a look into a solution.

**Comment by droyad** [comment]
@AdrianJSClark I had a passing thought that perhaps we should use Sprache instead of our own parser.

**Comment by dazinator** [comment]
@AdrianJSClark 
Seems like that could be a lot of effort! Our own parser has been established for a long time and many edge cases fixed. I'm guessing the odds are that if we moved to sprache the same kinds of edge cases as this may appear except we'd now have to extend sprache to deal with them. Perhaps that's a lot easier to do with sprache it being designed for the purpose. However our parser is pretty simple too imho - it's a glorified TextReader reading characters from a stream not too complex to work on really.. The good thing is we have regression tests so if you do think the effort of adopting sprache worthwhile then the risk of introducing instability is minimised. Perhaps just keep the existing parser around (marked as obsolete) alongside any sprache based parser just in case anyone directly relies on it for some reason

**Comment by AdrianJSClark** [comment]
@droyad I had considered that too, although I was going to use Sprache via Superpower. However I have an alternative.

As I'm sure you know, we parse the SQL for two purposes:

  1. To identify replacement tokens for our variable replacement
  1. In order to split statements into batches (in SQL Server that's splitting on "GO" statements)

Currently as I understand the code, these two purposes are handled using the same parsing logic. My plan (and the reason I assigned this to myself) is to split these two purposes into their own code. I expect that the Variable Substitution feature can be implemented using a simple regular expression based replacement. The second, splitting "GO" statements, isn't always as simple as it first appears so needs proper SQL parsing.

I plan to handle the SQL parsing with a Microsoft-supplied package called ["Microsoft.SqlServer.DacFx"](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx) which includes a T-SQL parser. This offloads the responsibility for writing a performant, resiliant, compliant parser. Obviously we will need to do variable substitution before we parse the SQL, otherwise the SQL may not be valid.

I've created a simple LINQPad-based proof-of-concept to split SQL into batches (including the problematic comment format described on this issue) using `Microsoft.SqlServer.DacFx` which you can see here: [DacFx Parsing LINQPad POC](http://share.linqpad.net/u2sqtq.linq)

Sorry I just grabbed the issue without this further explanation. What do you think?

**Comment by sungam3r** [comment]
The use of specific parsers for different databases can be really justified despite the emergence of additional dependencies. After all, code parsing is not the task of this project.

**Comment by droyad** [comment]
@AdrianJSClark Sounds good to me

**Comment by AdrianJSClark** [comment]
While examining the code to begin work on integrating `Microsoft.SqlServer.DacFx` I managed to fix the problem described in this issue. As such, the PR referenced above will resolve this issue.

I'll extract my comment about restructuring the SQL parsing into a new issue.
