### ISSUE TITLE
Why does Table Journal have a primary key field?

### ISSUE THREAD

**Issue by arabasso** [DbUp/DbUp#446]
Hello!

I started using DbUp in a project, and it creates a primary key field that apparently isn't used anywhere. Depending on the target database, in addition to this primary key, a trigger is created.

Looking at other migration models (such as FluentMigrator and Entity Framework), they do not create a primary key field.

I didn't get to analyze the DbUp source code, so I ask: is it really necessary to create a primary key field (and a trigger depending on the situation) for the library to work properly?

**Comment by droyad** [comment]
It likely isn't, but it should at least be unique to make sure we don't double up on scripts accidentally. Why wouldn't you create a primary key? (I'm primarily a SQL Server person).

**Comment by AdrianJSClark** [comment]
Looking at the code we do create a separate `Id` column as the primary key but only ever use the `ScriptName` column to check scripts. I would argue we'd be better making `ScriptName` the primary key because then we would be prevented from doubling up on scripts.

As it is [implemented in the `dbup-sqlserver` package](https://github.com/DbUp/DbUp/blob/master/src/dbup-sqlserver/SqlTableJournal.cs#L42-L45) the primary key doesn't help us do anything.

I'd certainly entertain a plan to get rid of the primary key. The table should absolutely have a uniqueness constraint of some description on the `ScriptName` column. If that comes from moving the primary key to that column, great. If it is just a unique constraint to avoid some undesired side affect, that's fine too.

**Comment by droyad** [comment]
Unless there is a good reason not to do this I don't want to change the status quo
