### ISSUE TITLE
Version 4.3.0 breaks DeployChanges.To.SqlDatabase(ConnectionString)

### ISSUE THREAD

**Issue by DecorteHannes** [DbUp/DbUp#469]
Works with version 4.2.0, but with version 4.3.0 =>
System.Data.SqlClient.SqlException: System.Data.SqlClient.SqlException: Cannot open database "[REMOVED_FOR_SECURITY]" requested by the login. The login failed.
Login failed for user 'NT AUTHORITY\NETWORK SERVICE'

var builder = DeployChanges.To.SqlDatabase(ConnectionString)

ConnectionString = "Server=(localdb)\\MSSQLLocalDB;Database=$(DatabaseName);Trusted_Connection=True;MultipleActiveResultSets=true;connect timeout=120;"

**Comment by droyad** [comment]
This is caused by #388. From the looks of it it's due to connection pooling (clearing all connections fixed the problem).

It only makes sense to check using the connection string directly if we can't access `master` (since we need access to `master` to create the DB). So I'm going to move it around a bit.
