### ISSUE TITLE
PlatformNotSupportedException on .NET 5.0

### ISSUE THREAD

**Issue by wintheriscomming** [DbUp/DbUp#546]
After upgrading to .NET 5 dbup fails during database upgrade with PlatformNotSupportedException, see stack trace bellow.

```
Upgrade failed due to an unexpected exception:
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at DbUp.SqlServer.SqlConnectionManager.<>c__DisplayClass0_0.<.ctor>b__0(IUpgradeLog log, DatabaseConnectionManager dbManager)
   at DbUp.Engine.Transactions.DelegateConnectionFactory.CreateConnection(IUpgradeLog upgradeLog, DatabaseConnectionManager databaseConnectionManager)
   at DbUp.Engine.Transactions.DatabaseConnectionManager.CreateConnection(IUpgradeLog upgradeLog)
   at DbUp.Engine.Transactions.DatabaseConnectionManager.OperationStarting(IUpgradeLog upgradeLog, List`1 executedScripts)
   at DbUp.Engine.UpgradeEngine.PerformUpgrade()
```

The issue can be solved by replacing NuGet package `System.Data.SqlClient` with `Microsoft.Data.SqlClient` (and changing namspaces accordingly), see PR #547.

**Comment by ABAG603** [comment]
@AdrianJSClark @droyad can this be taken as a priority? This could be a blocker for .Net 5 migration. Thanks.

**Comment by AdrianJSClark** [comment]
I'm confused about this error. I've upgraded a DbUp SQL Server project to .NET 5 and had absolutely no issues. I imagine that this issue has come up in a non-Windows binary, which `System.Data.SqlClient` doesn't support. In that way it isn't a blocker for .NET 5.0 migration any more than the same Windows dependency was a blocker for .NET Core 3.1 migration.

Changing to use `Microsoft.Data.SqlClient` will have to be a major release, because it is a giant change that must be communicated properly.

It also means that we will end up dropping some support for older .NET Framework targets, which `Microsoft.Data.SqlClient` does not support. This change was already being discussed for 5.0 in #432. That issue was suggesting we keep `netstandard1.3` compatibility in order to maintain the ability to work on Mono & Xamarin, however this target would need to be dropped in this case.

There were a few other changes which were planned before releasing a 5.0, including #431, however perhaps we could create a 5.0 pre-release version which includes the migration to `Microsoft.Data.SqlClient`? What do you think, @droyad?

**Comment by ABAG603** [comment]
@AdrianJSClark looks like you're totally right - I've updated my project that uses DbUp to .Net 5 today and everything's fine so far. But I'm targeting win-x64 runtime.

**Comment by wintheriscomming** [comment]
I think you can close this issue. After a long investigation it turned out to be an incorrect setting in a `Directory.Build.props` file, resulting in the transient dependency to `System.Data.SqlClient` package not being copied correctly.
Sorry ta have taken up your time!

**Comment by AdrianJSClark** [comment]
@wintheriscomming No worries! I'm very glad that you sorted things out. Thanks for popping back and letting us know.
