### ISSUE TITLE
question about DBUp.  Wasnt sure where to ask.  

### ISSUE THREAD

**Issue by llyons** [DbUp/DbUp#549]
if we had a DB and we needed to add some column updates and data to a table that was added a year ago for a release,  how does the developer know what has been done before to make sure the column or data updates dont cause conflicts?

what if they add it to an existing script that was used in the past or use the same name?

Im just asking since we are looking at dbup and have some large db releases where we have 50-100 different scripts and these kinds of releases up to 8 times a year

**Comment by AdrianJSClark** [comment]
Hi @llyons 

We try not to encourage questions in the issues here. There's a ["dbup" tag on StackOverflow](https://stackoverflow.com/questions/tagged/dbup) which might be the best place in the future.

As for your queries, hopefully this answers them for you.

The developer knows what has been done before because they both have the scripts as part of the project and also can execute them using DbUp to create a copy of the database themselves.

Each script is executed a single time in DbUp. By default, that's based on the script's file name so if you go back and edit an existing script those edits will never be applied. All scripts are executed against a database once. To add additional data you'd need to create a new script with a different name.

If you have a large number of scripts it is often best to place them in folders and ensure there's a clear naming guidance. The scripts are (in default configuration) sorted alphabetically by their path, so prefixing each script name with the date or an incrementing, zero-padded number is common.

**Comment by AdrianJSClark** [comment]
Thanks for the question @llyons. Hope you got the information you were looking for.
