### ISSUE TITLE
Question: plan to move off dotnetframework?

### ISSUE THREAD

**Issue by Justin-DynamicD** [DbUp/DbUp#558]
Are there any plans to get off of dotnet framework so that this tool can be run from multiple operating systems?  I have a lot of clients now that do all their builds and work from linux-based agents, so being able to bundle this tool into those build agents would be a big win.

**Comment by AdrianJSClark** [comment]
I don't think it is realistic to move completely away from .NET Framework support. There are lots of projects out there that are still using it very successfully with no plans to migrate away so DbUp should keep supporting them. This doesn't mean that the code can't be written in a way to support your goals.

There was discussion about moving to newer versions to allow use of newer features and reduce complexity in #432. I think if the repository split discussed in #431 was implemented we could take that opportunity of the major version bump (which would be required) to not only get rid of some of the very old platforms but also to make moves towards newer, cross-platform support.

For example, as part of the major release the `DbUp.SqlServer` package could change it's references to use the [Microsoft.Data.Client](https://www.nuget.org/packages/Microsoft.Data.SqlClient/) package instead of using `System.Data.Client`. This would break the Windows requirement for that particular database technology.

**Comment by Justin-DynamicD** [comment]
I read about the split and nearly commented in there on this issue, but felt it wasn't appropriate so made this ask instead.

Thanks for the viewpoint on development.  I would love to see a push for a newer standard, as at the end of the day most consumers of the tool are just downloading and executing a binary ... so they really don't care much about how it was built/compiled. I have clients right now who use MSSQL out of familiarity, but their app stack is all go.  They couldn't care less about what's under the hood ... just that dbup lets them push sql scripts in a structured manner. *shrug*.

**Comment by stevenwilliamsmis** [comment]
@AdrianJSClark I submitted a pull request yesterday before I saw this post #565 to add support of the Microsoft.Data.SqlClient package using compile flags to maintain backwards compatibility for Net 3.5 and Standard 1.3. 
 What do you mean when you stated above that updating would break the windows requirement?

**Comment by AdrianJSClark** [comment]
I meant that `Microsoft.Data.SqlClient` is designed to be cross-platform, however `System.Data.SqlClient` is not. So the dependency on Windows is broken when we upgrade.

I did see #565 come through, thanks for posting that.

**Comment by AdrianJSClark** [comment]
There is a `net6.0` target available which references `Microsoft.Data.SqlClient` as of #652.
