### ISSUE TITLE
Unable to replace system variables ex: $(system.DefaultWorkingDirectory)

### ISSUE THREAD

**Issue by Ganesh-Ponipireddy** [DbUp/DbUp#573]
I had tried many ways like passing below

In general powershell we use $(Env:system_DefaultWorkingDirectory) gives us the output. 
I had tried $SYSTEM_DEFAULTWORKINGDIRECTORY$ -- failed.
$ENV:SYSTEM_DEFAULTWORKINGDIRECTORY$ this also failed.
$ENV_SYSTEM_DEFAULTWORKINGDIRECTORY$ this also failed.

can some one help in fixing this. I need to replace system variables.

**Comment by AdrianJSClark** [comment]
The DbUp variable substitution doesn't automatically populate from System Environment Variables, so this is expected behaviour.

You can configure the variable values & names you'd like to pass through to scripts as part of building your upgrader.

Here's a sample that will simply echo the values given back to the log output. The important two lines are the "WithVariable" calls which tell DbUp what name you'd like it to look for and the replacement value. The format of variables within the SQL Script is the name of the variable delimited by a dollar sign ($) at either side (i.e. "$foo$" without quotes would be the variable name "foo").

```csharp
	var upgrader = DeployChanges.To.SqlDatabase(connectionString)
	                               .LogToTrace()
				       .JournalTo(new NullJournal())
				       .LogScriptOutput()

				       .WithVariable("Variable1", Environment.GetEnvironmentVariable("USERNAME"))
				       .WithVariable("Variable2", Environment.GetEnvironmentVariable("ProgramData"))

				       .WithScript("TestScript", @"
SELECT N'Variable Value 1' AS [Name], N'$Variable1$' AS [Value]
UNION
SELECT N'Variable Value 2' AS [Name], N'$Variable2$' AS [Value]
").Build();

	upgrader.PerformUpgrade();
```

**Comment by Ganesh-Ponipireddy** [comment]
@AdrianJSClark 
Thanks for your suggestion and help. I had added new parameters and assigned the system variable values to it. Used the newly created prams for replacing the values. 

This solved my problem.
