### ISSUE TITLE
[Docs] Difference to EF migrations

### ISSUE THREAD

**Issue by lonix1** [DbUp/DbUp#590]
I've searched the docs but cannot understand how DbUp differs to EF Core migrations. Why do users prefer this library to the native migrations functionality?

It might be good to include that in the FAQ section. Thanks!

**Comment by boraolim** [comment]
It is easier for me to use DbUp because the transaction log is very light in the database and allows me to create objects to my liking in an efficient way, which the Entity Framework does not do. It is better to use Native SQL to perform Database migrations smoothly and easily than to use source code that can only create objects in the DB.

**Comment by lonix1** [comment]
@boraolim So you must create migrations files by hand?

**Comment by Orkad** [comment]
@lonix1 you sure you really read the doc ?

**Comment by lonix1** [comment]
@Orkad Yes 10 days ago.

**Comment by lonix1** [comment]
@Orkad You've been very helpful, thanks.
