### ISSUE TITLE
Question: Does DbUp support SQL Server 2019?

### ISSUE THREAD

**Issue by dbruk9** [DbUp/DbUp#597]
I see that SQL Server 2019 was not listed as [supported](https://dbup.readthedocs.io/en/latest/supported-databases/) .
I have been testing it with SQL Server 2019 and see no issues.   I was wondering what it would take to get SQL Server 2019 officially supported? Is it a testing effort or are there known issues with DbUp and SQL Server 2019?

**Comment by sungam3r** [comment]
This project has long stopped active development. This is the main reason.

**Comment by AdrianJSClark** [comment]
Hi @dbruk9,

There is no reason that DbUp will not work with SQL Server 2019. It will work on any SQL Server supported by the underlying SQL Client.

Since you've seen no issues I'd happily accept a PR to update the documentation.

As far as "official support" goes, this project is the work of volunteers so officially there's no support. :)

**Comment by dbruk9** [comment]
Thanks for the replies @sungam3r and @AdrianJSClark! I have used it extensively on SQL Server 2019 and saw no issues related to SQL Server 2019. I'll submit a PR to get it added to the docs.
