### ISSUE TITLE
Cassandra support 

### ISSUE THREAD

**Issue by MOSMekawy** [DbUp/DbUp#600]
As far as I know there's no schema migration tool that supports CQL for C#. Would it be possible to add CQL support for DbUp ?

**Comment by AdrianJSClark** [comment]
DbUp is essentially a framework to execute a collection of text-based script files. Language (i.e. SQL) level manipulation almost all happens as part of that particular database's support.

So certainly if there is a .NET library for the Cassandra database the various interfaces should be able to be implemented.

I've never used Cassandra so I won't be able to contribute an implementation personally.

**Comment by MOSMekawy** [comment]
There is actually .NET Driver for Cassandra. I am not super knowledgeable about Cassandra but I would be willing to give it a go.

**Comment by AdrianJSClark** [comment]
You're very welcome to give it a try if it is something you'd like to use. There's several different providers here in the repository which you can look at to help you.

The basics for building a provider are:

1. Create Cassandra-specific implementations for the following interfaces:
    - `DbUp.Engine.Transactions.IConnectionManager` - this manages connections to the database
    - `DbUp.Engine.IScriptExecutor` - this executes the scripts against the database
    - `DbUp.Engine.IJournal` - this records that the script has been executed or produces the list of previously executed scripts
2. Create an extension method named like the database on the `DbUp.Builder.SupportedDatabases` object that returns an instance of `DbUp.Builder.UpgradeEngineBuilder` which is configured with the three implementations above

It has been a while since I've had to go through the whole stack like that, but I think that is about it. I'm not sure if you'll hit any blockers in the DbUp core features, but if you do raise them and perhaps there are work-arounds. The core was originally written for SQL Server, so is very orientated around SQL-like databases.

**Comment by MOSMekawy** [comment]
Seems straightforward enough. Thanks for the explanation.

**Comment by sungam3r** [comment]
@MOSMekawy Please see #431. As I can see the plan is to move providers into separate repos.
