### ISSUE TITLE
ExtendedSocketException: "A non-blocking socket operation could not be executed immediately. [::1]:5432"

### ISSUE THREAD

**Issue by SeppPenner** [DbUp/DbUp#603]
We are using pretty much the standard / example code with DbUp and Postgres:

### Code:
```csharp
using DbUp;
using System;
using System.Reflection;

public static class DatabaseUpdater
{
    public static void RunUpdate(string[] args)
    {
        var upgradeEngine =
            DeployChanges.To
                .PostgresqlDatabase("Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=test;Pooling=true;Timezone=Europe/Berlin;Enlist=false;Maximum Pool Size=400;Include Error Detail=true")
                .WithScriptsEmbeddedInAssembly(Assembly.GetExecutingAssembly())
                .JournalToPostgresqlTable("public", "databaseversion")
                .LogToConsole()
                .Build();

        var result = upgradeEngine.PerformUpgrade();

        if (!result.Successful)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(result.Error);
            Console.ResetColor();
            return;
        }

        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine("Success!");
        Console.ResetColor();
    }
}
```

and get the following error everytime the method for the database update is called:
> System.Net.Internals.SocketExceptionFactory.ExtendedSocketException: "Ein nicht blockierender Socketvorgang konnte nicht sofort ausgeführt werden. [::1]:5432"

English:
> System.Net.Internals.SocketExceptionFactory.ExtendedSocketException: "A non-blocking socket operation could not be executed immediately. [::1]:5432"

This doesn't seem to be a bug as the update works properly, but the error is a bit disturbing...

### Version-Information:
Net Runtime: Net 6.0
dbup-postgresql: 4.5.0

**Comment by AdrianJSClark** [comment]
Are you seeing that error in logging?

The `dbup-postgresql` package utilises [the Npgsql package](https://www.nuget.org/packages/Npgsql/) in order to execute all operations against the database. It appears from searching their issues that [the "ExtendedSocketException" is considered an internal exception](https://github.com/npgsql/npgsql/issues/3295#issuecomment-723032142) and only a concern if it bubbles up to your code.

If you are relying on the transitive dependency to include `Npgsql` in your project (in other words, if you've installed `dbup-postgresql` and not explicitly added a version of `Npgsql`) then you might want to try installing the latest version. I'm sure that it will work (if not, file a separate issue and someone can investigate) and perhaps this issue you are seeing is resolved in the newer `Npgsql` code.

The `dbup-postgresql` package hasn't had any changes for a while so the version defined in the dependency, the one you get by default with NuGet's "minimum version" policy, is quite old.

**Comment by SeppPenner** [comment]
> The dbup-postgresql package utilises the Npgsql package in order to execute all operations against the database. It appears from searching their issues that the "ExtendedSocketException" is considered an internal exception and only a concern if it bubbles up to your code.

Yes, I can only see the exception within the debugger (and with "all exceptions" turned on), but not in the productive log.

> The dbup-postgresql package utilises the Npgsql package in order to execute all operations against the database. It appears from searching their issues that the "ExtendedSocketException" is considered an internal exception and only a concern if it bubbles up to your code.

I tried that (The dependency on Npgsql is now in the project and up-to-date, version 6.0.3), but the same error occurs.

> The dbup-postgresql package hasn't had any changes for a while so the version defined in the dependency, the one you get by default with NuGet's "minimum version" policy, is quite old.

The used Npgsql version in there is 3.2.6 (As you said, quite old).


Ok, if it's a Npgsql internal issue, I'm fine with that. I was just curious where it comes from and if it might have an impact on the project (Although I didn't yet see something like that).
