### ISSUE TITLE
SqlClient library mismatch between .NetStandard and .Net6 targets in dbup-sqlserver 5.0.8 Nuget package

### ISSUE THREAD

**Issue by smarcaurele** [DbUp/DbUp#674]
I tried to update the dbup-sqlserver nuget package today from version 4.5.0 to version 5.0.8.

I have a .NetStandard class library that includes the dbup-sqlserver nuget package and a .Net6 console app that references the .NetStandard class library.

After upgrading the .NetStandard project to version 5.0.8, I can no longer compile the .Net 6 project with it complaining that I have no reference to System.Data.SqlClient.

It seems that the problem is that the 5.0.8 package lists System.Data.SqlClient as a dependency for NetStandard projects, but lists Microsoft.Data.SqlClient as a dependency for Net6 projects.

So my NetStandard library creates a System.Data.SqlClient.SqlConnectionStringBuilder that the Net6 project cannot deal with since it only has access to Microsoft.Data.SqlClient.

There are many ways I can work around this, but I think that upgrading Nuget packages should not break existing projects.  It seems that you should be able to use NetStandard libraries with Net6 projects.

**Comment by sungam3r** [comment]
> I tried to update the dbup-sqlserver nuget package today from version 4.5.0 to version 5.0.8.
> but I think that upgrading Nuget packages should not break existing projects.

You are right about the reason. Regarding update - major version was changed to indicate **breaking changes**. You may add required dependency in your project on your own.

**Comment by AdrianJSClark** [comment]
@smarcaurele You've correctly identified the issue as that the `netstandard2.0` target and `net6.0` target referencing the separate versions of the SQL Server library. This is intentional to remain more compatible for older frameworks while enabling use of the newer library for .NET 6 applications.

You have a couple of options:

- If you do not need the `netstandard2.0` compatibility, simply target your library as `net6.0` to match your executable project.
- If you do need `netstandard2.0` for another project, dual-target that library as both `netstandard2.0` and `net6.0` so your .NET Framework clients pick up the `System.Data` reference and the .NET 6 clients will pick up the `Microsoft.Data` reference.

Either of these options should match the dependencies up.

**Comment by sungam3r** [comment]
Closed as answered.
