### ISSUE TITLE
Build for .Net 7 and .Net 8

### ISSUE THREAD

**Issue by mortenf1984** [DbUp/DbUp#717]
I see that DbUp does not build a .Net 7 version, only .Net 6. Is it possible to get a .Net7 version? That is using Microsoft.Data.SqlClient? And .Net 8 is coming in November hopefully, get it for that one also?

Reason is that we do not want to accidentally end up using System.Data.SqlClient.

**Comment by Havagan** [comment]
> Best solution would be to migrate the functionallity of SqlContextUpgradeLog to Microsoft.Data.SqlClient

I can do that if you want to assign me to this task.

**Comment by Havagan** [comment]
@mjauernig Digging more into it and it looks like ContextConnection, which is what enabled the SqlContext, is not supported in Microsoft.Data.SqlClient and there are no plans to do so since it only appears to be used when using .NET as a compiled CLR Stored Procedure.

https://github.com/dotnet/SqlClient/issues/73#issuecomment-713300875

Using SqlContext's only use case is from within a CLR stored procedure and you can see that when running that logger in .NET 462, it throws an error:

```
System.InvalidOperationException : The requested operation requires a SqlClr context, which is only available when running in the Sql Server process.
```

What's the likelihood of someone running DbUp to deploy scripts as a deployed SQL CLR assembly to execute it within the context of a SQL Server instance? This seems like a serious edge case that, IMO, isn't really worth supporting as it seems outside of the core purpose of DbUp.

**Comment by mjauernig** [comment]
@Havagan Thanks for the deeper research. 

So you are suggesting that we can drop `System.Data.SqlClient` for the next `breaking` release?

**Comment by twenzel** [comment]
@Havagan I would suggest to drop `System.Data.SqlClient`. We might provide the SqlContextUpgradeLog functionality as an extension in a separate project if the community still need it.

**Comment by Havagan** [comment]
@mjauernig Yes, we can drop ```System.Data.SqlClient``` in the next ```breaking``` release.

I'm in agreement with @twenzel.

**Comment by droyad** [comment]
This will be fixed with https://github.com/DbUp/dbup-sqlserver/issues/15
