### ISSUE TITLE
Ability to customize ScriptName when using a code-based script

### ISSUE THREAD

**Issue by mcolebiltd** [DbUp/DbUp#756]
We are currently using script based migrations and use a file name scheme of `yyyy-mm-dd-description.sql` to ensure scripts are executed in the sequence we expect. We would like to start using code-based migrations as well, but unfortunately we cannot create class names that start with a number so it is incompatible with our current scheme.

I would like to propose any of the following:
1) IScript interface provides a ScriptName string property that the engine respects when executing scripts.
2) An optional Attribute compatible with script classes that would provide the same as option 1.
3) When running code-based scripts, the engine could be configurable to use the filename of the class instead of the class name.

Or perhaps there's existing functionality that I am overlooking?

**Comment by mjauernig** [comment]
Hi,

I think you can solve this problem by naming the files correctly. I also ran into this a few years ago and now I use this naming scheme.

`Scripts\Jyyyy\Syyyy_mm_dd_nn_description.sql`

- `Scripts` The base folder of the scripts.
- `J` Just a `J`, because C# doesn't allow namespaces with a starting number.
- `yyyy` current year
- `S` is just a S, because C# doesn't allow class names with a starting number.
- `yyyy` current year
- `_` is an underscore instead of aminus, because minus is also an non-permitted character in class names.
- `mm` current month
- `dd` current day
- `nn` incremental number, starting with `01` on each new day. Use  with two digits, because of number sorting if you have more than 9 scripts on a day.
- `description` a keyword that helps to identify the script.

As result you will get something like this:
<img width="180" alt="image" src="https://github.com/DbUp/DbUp/assets/7187699/25c2dabb-c53f-4ff7-b3b2-64465851a633">

The namespace is the basefolder + each subfolder. The classname is as above.
<img width="248" alt="image" src="https://github.com/DbUp/DbUp/assets/7187699/916bb67b-c61c-4ab6-b281-8ef0b2861038">

The SchemaVersion table then looks like 
<img width="474" alt="image" src="https://github.com/DbUp/DbUp/assets/7187699/ceeb3a06-8952-4b4c-97f7-8759ab3deedf">

P.S.
Don't get confused with the year 2030, the sample is from a developer machine.

**Comment by mcolebiltd** [comment]
> Hi,
> 
> I think you can solve this problem by naming the files correctly. I also ran into this a few years ago and now I use this naming scheme.
> 
> `Scripts\Jyyyy\Syyyy_mm_dd_nn_description.ext`
> 
> * `Scripts` The base folder of the scripts.
> * `J` Just a `J`, because C# doesn't allow namespaces with a starting number.
> * `yyyy` current year
> * `S` is just a S, because C# doesn't allow class names with a starting number.
> * `yyyy` current year
> * `_` is an underscore instead of aminus, because minus is also an non-permitted character in class names.
> * `mm` current month
> * `dd` current day
> * `nn` incremental number, starting with `01` on each new day. Use  with two digits, because of number sorting if you have more than 9 scripts on a day.
> * `description` a keyword that helps to identify the script.
> * `ext` The file extension. `sql` for sql files. `cs` for c# files.
> 
> As result you will get something like this: <img alt="image" width="180" src="https://user-images.githubusercontent.com/7187699/281663962-25c2dabb-c53f-4ff7-b3b2-64465851a633.png">
> 
> The namespace is the basefolder + each subfolder. The classname is as above. <img alt="image" width="248" src="https://user-images.githubusercontent.com/7187699/281664407-916bb67b-c61c-4ab6-b281-8ef0b2861038.png">
> 
> The SchemaVersion table then looks like <img alt="image" width="474" src="https://user-images.githubusercontent.com/7187699/281665452-ceeb3a06-8952-4b4c-97f7-8759ab3deedf.png">
> 
> P.S. Don't get confused with the year 2030, the sample is from a developer machine.

Thanks for the input. I also considered what you are suggesting, but considered that more of a work-around and I was hoping to either find or help create a more direct solution.

**Comment by mcolebiltd** [comment]
It appears that I can create a custom `IScriptProvider` and override the default functionality. I am happy with this approach so I will be closing this.

**Comment by nomba** [comment]
Hi everyone!
I'm a new user of DbUp and encountered the same issue as @mcolebiltd. I have a few questions:

@mjauernig,

1. In your approach (Scripts\Jyyyy\Syyyy_mm_dd_nn_description.ext), how do you ensure consistency in naming and file structure? I mean, if you have more than one developer on the team, the likelihood of incorrect naming increases. Do you use any tools to generate a script template or a Roslyn analyzer to check it?
2. How can I exclude the assembly name of scripts/code in the journal table? This is crucial because we’re planning a project refactor, and the assembly name may change.

Thank you in advance!
